services:
  pm-reading-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm-playbooks-app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
